import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

// yeh standalone script hai  sirf ek baar run kiya tha exercises upload karne ke liye
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  final db = FirebaseFirestore.instance;
  final exercises = _allExercises();

  int count = 0;
  for (final exercise in exercises) {
    await db.collection('exercises').add(exercise);
    count++;
    debugPrint('Uploaded $count/${exercises.length}: ${exercise['name']}');
  }

  debugPrint('Done — uploaded $count exercises');
}

// Firebase Storage ka full streaming URL banao  encoded path ke saath
String _videoUrl(String path) {
  final encoded = Uri.encodeComponent(path);
  return 'https://firebasestorage.googleapis.com/v0/b/muscle-rich.firebasestorage.app/o/$encoded?alt=media';
}

// 102 exercises ka full list  name, bodyPart, Level, description aur videoPath
List<Map<String, dynamic>> _allExercises() {
  return [
    // CHEST
    {
      'name': 'Push Up',
      'bodyPart': 'Chest',
      'Level': 'Beginner',
      'description': 'The most fundamental upper body exercise. Start in a plank position with hands slightly wider than shoulder-width. Lower your chest to the floor by bending your elbows, keeping your body rigid, then press back up explosively.',
      'videoPath': _videoUrl('videos/chest/Chest/push up_x264 (2).mp4'),
    },
    {
      'name': 'Incline Push Up',
      'bodyPart': 'Chest',
      'Level': 'Beginner',
      'description': 'A beginner-friendly push up variation with hands elevated on a bench or step. Targets the lower chest and triceps.',
      'videoPath': _videoUrl('videos/chest/Chest/Incline Push ups (2).mp4'),
    },
    {
      'name': 'Wide Push Up',
      'bodyPart': 'Chest',
      'Level': 'Beginner',
      'description': 'A push up variation with hands placed wider than shoulder width. Places greater stress on the chest.',
      'videoPath': _videoUrl('videos/chest/Chest/wide push ups_x264 (2).mp4'),
    },
    {
      'name': 'Decline Push Up',
      'bodyPart': 'Chest',
      'Level': 'Intermediate',
      'description': 'Performed with feet elevated on a bench. Shifts emphasis to the upper chest and front deltoids.',
      'videoPath': _videoUrl('videos/chest/Chest/Decline Push UP_x264 (2).mp4'),
    },
    {
      'name': 'Dumbbell Chest Press Flat',
      'bodyPart': 'Chest',
      'Level': 'Beginner',
      'description': 'Lie on a flat bench holding a dumbbell in each hand at chest level. Press both dumbbells up until arms are fully extended.',
      'videoPath': _videoUrl('videos/chest/Chest/dumbbell chest press flat_x264 (2).mp4'),
    },
    {
      'name': 'Dumbbell Chest Press Incline',
      'bodyPart': 'Chest',
      'Level': 'Intermediate',
      'description': 'Set a bench to 30-45 degrees. Press dumbbells overhead targeting the upper chest.',
      'videoPath': _videoUrl('videos/chest/Chest/dumbbell chest press incline bench_x264 (2).mp4'),
    },
    {
      'name': 'Dumbbell Fly Flat Bench',
      'bodyPart': 'Chest',
      'Level': 'Intermediate',
      'description': 'Lie on a flat bench. Lower dumbbells in a wide arc until you feel a deep stretch in your chest.',
      'videoPath': _videoUrl('videos/chest/Chest/dumbell fly flat bench_x264 (2).mp4'),
    },
    {
      'name': 'Dumbbell Fly Incline Bench',
      'bodyPart': 'Chest',
      'Level': 'Intermediate',
      'description': 'Performed on an incline bench targeting the upper chest with a deep stretch.',
      'videoPath': _videoUrl('videos/chest/Chest/dumbell fly incline bench_x264 (2).mp4'),
    },
    {
      'name': 'Barbell Bench Press',
      'bodyPart': 'Chest',
      'Level': 'Intermediate',
      'description': 'The benchmark chest exercise. Lie on a flat bench and press the barbell from chest to full extension.',
      'videoPath': _videoUrl('videos/chest/Chest/barbell bench press_x264 (2).mp4'),
    },
    {
      'name': 'Barbell Bench Press Incline',
      'bodyPart': 'Chest',
      'Level': 'Advanced',
      'description': 'Set the bench to 30-45 degrees. Targets the upper chest.',
      'videoPath': _videoUrl('videos/chest/Chest/barbell bench press incline_x264 (2).mp4'),
    },
    {
      'name': 'Barbell Bench Press Decline',
      'bodyPart': 'Chest',
      'Level': 'Advanced',
      'description': 'Performed on a decline bench targeting the lower chest.',
      'videoPath': _videoUrl('videos/chest/Chest/barbell bench press decline_x264 (2).mp4'),
    },
    {
      'name': 'Cable Fly Machine Mid',
      'bodyPart': 'Chest',
      'Level': 'Intermediate',
      'description': 'Set cables at mid height. Bring both handles together maintaining constant tension throughout.',
      'videoPath': _videoUrl('videos/chest/Chest/cable fly machine mid_x264 (2).mp4'),
    },
    {
      'name': 'Cable Machine High to Low',
      'bodyPart': 'Chest',
      'Level': 'Intermediate',
      'description': 'Set the cables high and pull them downward targeting the lower chest fibres.',
      'videoPath': _videoUrl('videos/chest/Chest/cable machine high to low_x264 (2).mp4'),
    },
    {
      'name': 'Machine Chest Press Flat',
      'bodyPart': 'Chest',
      'Level': 'Beginner',
      'description': 'Sit in the chest press machine. Push handles forward until arms are fully extended.',
      'videoPath': _videoUrl('videos/chest/Chest/machine chest press flat_x264 (2).mp4'),
    },
    {
      'name': 'Peck Deck Fly Machine',
      'bodyPart': 'Chest',
      'Level': 'Beginner',
      'description': 'Sit in the pec deck machine. Bring the pads together squeezing your chest.',
      'videoPath': _videoUrl('videos/chest/Chest/peck deck fly machine_x264 (2).mp4'),
    },
    {
      'name': 'Chest Dip',
      'bodyPart': 'Chest',
      'Level': 'Advanced',
      'description': 'Using parallel bars with a forward lean to target chest over triceps.',
      'videoPath': _videoUrl('videos/chest/Chest/chest dip_x264 (2).mp4'),
    },
    {
      'name': 'Smith Machine Press Flat',
      'bodyPart': 'Chest',
      'Level': 'Intermediate',
      'description': 'Lie on a flat bench inside the Smith machine. Fixed bar path allows full focus on chest activation.',
      'videoPath': _videoUrl('videos/chest/Chest/smith machine press flat_x264 (2).mp4'),
    },
    // BACK
    {
      'name': 'Lat Pull Down Normal Grip',
      'bodyPart': 'Back',
      'Level': 'Beginner',
      'description': 'Foundational pull exercise. Pull the bar to your upper chest driving elbows toward hips.',
      'videoPath': _videoUrl('videos/back/lat pull down normal grip_x264 (2).mp4'),
    },
    {
      'name': 'Lat Pull Down Wide Grip',
      'bodyPart': 'Back',
      'Level': 'Beginner',
      'description': 'Wide grip increases range of motion emphasising the outer lats.',
      'videoPath': _videoUrl('videos/back/lat pull down wide grip_x264 (2).mp4'),
    },
    {
      'name': 'Lat Pull Down Close Grip',
      'bodyPart': 'Back',
      'Level': 'Beginner',
      'description': 'Close grip allows greater range of motion targeting lower lats and biceps.',
      'videoPath': _videoUrl('videos/back/lat pull down close grip_x264 (2).mp4'),
    },
    {
      'name': 'Seated Cable Row',
      'bodyPart': 'Back',
      'Level': 'Beginner',
      'description': 'Pull the handle to lower chest squeezing shoulder blades. Builds mid-back thickness.',
      'videoPath': _videoUrl('videos/back/seated normal grip row machine_x264 (2).mp4'),
    },
    {
      'name': 'Assisted Pull Up Normal Grip',
      'bodyPart': 'Back',
      'Level': 'Beginner',
      'description': 'Machine counterbalances bodyweight. Perfect stepping stone to full pull ups.',
      'videoPath': _videoUrl('videos/back/assisted pull up normal grip_x264 (2).mp4'),
    },
    {
      'name': 'Dumbbell Single Arm Row',
      'bodyPart': 'Back',
      'Level': 'Intermediate',
      'description': 'Unilateral movement builds back thickness and prevents muscle imbalances.',
      'videoPath': _videoUrl('videos/back/dumbell single arm row right_x264 (2).mp4'),
    },
    {
      'name': 'Single Arm Bench Bent Over Row',
      'bodyPart': 'Back',
      'Level': 'Intermediate',
      'description': 'One hand on bench for support. Row dumbbell toward lower ribcage.',
      'videoPath': _videoUrl('videos/back/single arm bench bent over row right_x264 (2).mp4'),
    },
    {
      'name': 'Pull Up Normal Grip',
      'bodyPart': 'Back',
      'Level': 'Intermediate',
      'description': 'Gold standard back exercise. Pull chest to bar driving elbows down.',
      'videoPath': _videoUrl('videos/back/pull up normal grip_x264 (2).mp4'),
    },
    {
      'name': 'Pull Up Wide Grip',
      'bodyPart': 'Back',
      'Level': 'Advanced',
      'description': 'Maximum stress on outer lats developing the V-taper shape.',
      'videoPath': _videoUrl('videos/back/pull up wide grip_x264 (2).mp4'),
    },
    {
      'name': 'Assisted Chin Up Reverse Grip',
      'bodyPart': 'Back',
      'Level': 'Beginner',
      'description': 'Supinated grip recruits biceps more. Great for beginners building pulling strength.',
      'videoPath': _videoUrl('videos/back/assisted chin up normal width reverse grip_x264 (2).mp4'),
    },
    {
      'name': 'Romanian Deadlift Barbell',
      'bodyPart': 'Back',
      'Level': 'Intermediate',
      'description': 'Hinge at hips keeping back flat. Targets hamstrings, glutes and lower back.',
      'videoPath': _videoUrl('videos/back/romanian deadlift babell_x264 (2).mp4'),
    },
    {
      'name': 'Romanian Deadlift Dumbbell',
      'bodyPart': 'Back',
      'Level': 'Intermediate',
      'description': 'Dumbbell version - easier to control for beginners learning the hip hinge.',
      'videoPath': _videoUrl('videos/back/romanian deadlift dumbell _x264 (2).mp4'),
    },
    {
      'name': 'V Bar Lat Pull Down',
      'bodyPart': 'Back',
      'Level': 'Intermediate',
      'description': 'Neutral grip attachment. Natural arm position allows heavier loading.',
      'videoPath': _videoUrl('videos/back/v bar lat pull down 1_x264 (2).mp4'),
    },
    {
      'name': 'Straight Bar Cable Row Wide Grip',
      'bodyPart': 'Back',
      'Level': 'Intermediate',
      'description': 'Wide overhand grip targets upper back and rear deltoids.',
      'videoPath': _videoUrl('videos/back/straight bar cable row wide grip 01_x264 (2).mp4'),
    },
    {
      'name': 'Trap Bar Deadlift',
      'bodyPart': 'Back',
      'Level': 'Advanced',
      'description': 'More upright position than conventional deadlift reducing lower back stress.',
      'videoPath': _videoUrl('videos/back/trap bar dead lift 1_x264 (2).mp4'),
    },
    {
      'name': 'Lying Back Extension',
      'bodyPart': 'Back',
      'Level': 'Beginner',
      'description': 'Lie face down and lift arms and legs simultaneously. Strengthens erector spinae.',
      'videoPath': _videoUrl('videos/back/lying back extension_x264 (2).mp4'),
    },
    // LEGS
    {
      'name': 'Bodyweight Squats',
      'bodyPart': 'Legs',
      'Level': 'Beginner',
      'description': 'Foundation of lower body training. Master this before adding weight.',
      'videoPath': _videoUrl('videos/legs/Legs/bodyweight squats_x264 (2).mp4'),
    },
    {
      'name': 'Glute Bridge',
      'bodyPart': 'Legs',
      'Level': 'Beginner',
      'description': 'Drive hips up squeezing glutes. Essential glute activation exercise.',
      'videoPath': _videoUrl('videos/legs/Legs/glute bridge (2).mp4'),
    },
    {
      'name': 'Wall Sit',
      'bodyPart': 'Legs',
      'Level': 'Beginner',
      'description': 'Hold parallel position against wall. Builds quad endurance.',
      'videoPath': _videoUrl('videos/legs/Legs/wall sit_x264 (2).mp4'),
    },
    {
      'name': 'Dumbbell Squats',
      'bodyPart': 'Legs',
      'Level': 'Beginner',
      'description': 'Hold dumbbells at sides. Added weight increases training stimulus.',
      'videoPath': _videoUrl('videos/legs/Legs/Dumbbell Squats_x264 (2).mp4'),
    },
    {
      'name': 'Dumbbell Lunge Alternating',
      'bodyPart': 'Legs',
      'Level': 'Beginner',
      'description': 'Trains each leg independently fixing imbalances and improving balance.',
      'videoPath': _videoUrl('videos/legs/Legs/Dumbbell Lunge Alternating on the spot_x264 (2).mp4'),
    },
    {
      'name': 'Goblet Squat Dumbbell',
      'bodyPart': 'Legs',
      'Level': 'Beginner',
      'description': 'Hold dumbbell at chest. Counterbalance helps maintain upright torso.',
      'videoPath': _videoUrl('videos/legs/Legs/goblet squats dumbells_x264 (2).mp4'),
    },
    {
      'name': 'Leg Press Machine Normal Stance',
      'bodyPart': 'Legs',
      'Level': 'Intermediate',
      'description': 'Feet shoulder-width apart. Heavy leg loading without spinal compression.',
      'videoPath': _videoUrl('videos/legs/Legs/leg press machine normal stance_x264 (2).mp4'),
    },
    {
      'name': 'Leg Extension Machine',
      'bodyPart': 'Legs',
      'Level': 'Intermediate',
      'description': 'Primary isolation exercise for the quadriceps.',
      'videoPath': _videoUrl('videos/legs/Legs/leg extension machine_x264 (2).mp4'),
    },
    {
      'name': 'Lying Leg Curl Machine',
      'bodyPart': 'Legs',
      'Level': 'Intermediate',
      'description': 'Premier isolation exercise for the hamstrings.',
      'videoPath': _videoUrl('videos/legs/Legs/lying leg curl machine_x264 (2).mp4'),
    },
    {
      'name': 'Barbell Hip Thrust',
      'bodyPart': 'Legs',
      'Level': 'Intermediate',
      'description': 'Most effective exercise for glute activation and development.',
      'videoPath': _videoUrl('videos/legs/Legs/Barbell Hip Thrust_x264 (2).mp4'),
    },
    {
      'name': 'Barbell Squats',
      'bodyPart': 'Legs',
      'Level': 'Intermediate',
      'description': 'King of compound movements for lower body strength and mass.',
      'videoPath': _videoUrl('videos/legs/Legs/barbell squats_x264 (2).mp4'),
    },
    {
      'name': 'Bulgarian Split Squat Dumbbell',
      'bodyPart': 'Legs',
      'Level': 'Intermediate',
      'description': 'Rear foot elevated. Isolates each leg placing enormous stress on quads and glutes.',
      'videoPath': _videoUrl('videos/legs/Legs/dumbell bulgarian split squat_x264 (2).mp4'),
    },
    {
      'name': 'Jump Squats',
      'bodyPart': 'Legs',
      'Level': 'Intermediate',
      'description': 'Explosive squat jump. Develops lower body power and fast-twitch recruitment.',
      'videoPath': _videoUrl('videos/legs/Legs/Jump Squats bodyweight_x264 (2).mp4'),
    },
    {
      'name': 'Hack Squat Machine',
      'bodyPart': 'Legs',
      'Level': 'Advanced',
      'description': 'Heavy quad loading without the spinal load of barbell squats.',
      'videoPath': _videoUrl('videos/legs/Legs/hack squats machine_x264 (2).mp4'),
    },
    {
      'name': 'Barbell Front Squat',
      'bodyPart': 'Legs',
      'Level': 'Advanced',
      'description': 'Front rack position demands extremely upright torso. More quad focused than back squat.',
      'videoPath': _videoUrl('videos/legs/Legs/barbell front squat (2).mp4'),
    },
    {
      'name': 'Single Leg Romanian Deadlift Dumbbell',
      'bodyPart': 'Legs',
      'Level': 'Advanced',
      'description': 'Unilateral hip hinge. Trains hamstrings and glutes while challenging balance.',
      'videoPath': _videoUrl('videos/legs/Legs/single leg romanian deadlift dumbbell right_x264 (2).mp4'),
    },
    {
      'name': 'Box Jump',
      'bodyPart': 'Legs',
      'Level': 'Advanced',
      'description': 'Explosive jump onto a box. Develops maximum lower body power.',
      'videoPath': _videoUrl('videos/legs/Legs/box jump_x264 (2).mp4'),
    },
    {
      'name': 'Standing Calf Raises',
      'bodyPart': 'Legs',
      'Level': 'Beginner',
      'description': 'Rise onto toes as high as possible. Targets gastrocnemius and soleus.',
      'videoPath': _videoUrl('videos/legs/Legs/standing calf raises (2).mp4'),
    },
    // ARMS
    {
      'name': 'Dumbbell Bicep Curl',
      'bodyPart': 'Arms',
      'Level': 'Beginner',
      'description': 'Classic bicep exercise. Curl both weights keeping upper arms still.',
      'videoPath': _videoUrl('videos/arms/biceps/dumbell curls_x264 (2).mp4'),
    },
    {
      'name': 'Alternating Bicep Curl Standing',
      'bodyPart': 'Arms',
      'Level': 'Beginner',
      'description': 'Curl one dumbbell at a time. Supinate wrist at top for maximum activation.',
      'videoPath': _videoUrl('videos/arms/biceps/alternate biceps curl standing dumbbells_x264 (2).mp4'),
    },
    {
      'name': 'Hammer Curl Alternating',
      'bodyPart': 'Arms',
      'Level': 'Beginner',
      'description': 'Neutral grip targets brachialis and brachioradialis adding arm thickness.',
      'videoPath': _videoUrl('videos/arms/biceps/alternate hammer curl standing dumbbells_x264 (2).mp4'),
    },
    {
      'name': 'Biceps Curl Cable',
      'bodyPart': 'Arms',
      'Level': 'Beginner',
      'description': 'Cable maintains constant tension unlike dumbbells. Excellent for bicep development.',
      'videoPath': _videoUrl('videos/arms/biceps/biceps curl cable_x264 (2).mp4'),
    },
    {
      'name': 'Barbell Bicep Curl Normal Grip',
      'bodyPart': 'Arms',
      'Level': 'Intermediate',
      'description': 'Allows heavier loads than dumbbells. Most efficient tool for overall bicep mass.',
      'videoPath': _videoUrl('videos/arms/biceps/barbell biceps curl normal grip 2_x264 (2).mp4'),
    },
    {
      'name': 'EZ Bar Bicep Curl Normal Grip',
      'bodyPart': 'Arms',
      'Level': 'Intermediate',
      'description': 'Angled grips reduce wrist stress compared to straight barbell.',
      'videoPath': _videoUrl('videos/arms/biceps/Ez bar biceps curl normal grip 1_x264 (2).mp4'),
    },
    {
      'name': 'Preacher Curl Barbell',
      'bodyPart': 'Arms',
      'Level': 'Intermediate',
      'description': 'Bench locks upper arms eliminating momentum. Forces maximum bicep isolation.',
      'videoPath': _videoUrl('videos/arms/biceps/preacher curl barbell_x264 (2).mp4'),
    },
    {
      'name': 'Concentration Curl Dumbbell',
      'bodyPart': 'Arms',
      'Level': 'Intermediate',
      'description': 'Elbow braced against thigh. Complete isolation of each arm.',
      'videoPath': _videoUrl('videos/arms/biceps/concentration curls dumbbell_x264 (2).mp4'),
    },
    {
      'name': 'Spider Curl Barbell',
      'bodyPart': 'Arms',
      'Level': 'Advanced',
      'description': 'Face down on incline bench. Biceps under maximum tension at full extension.',
      'videoPath': _videoUrl('videos/arms/biceps/spider curl barbell_x264 (2).mp4'),
    },
    {
      'name': 'Bench Tricep Dip Straight Legs',
      'bodyPart': 'Arms',
      'Level': 'Beginner',
      'description': 'Hands on bench edge, legs straight. Foundational tricep bodyweight exercise.',
      'videoPath': _videoUrl('videos/arms/triceps/bench triceps dip straight legs_x264 (2).mp4'),
    },
    {
      'name': 'Cable Tricep Push Down Straight Bar',
      'bodyPart': 'Arms',
      'Level': 'Beginner',
      'description': 'Elbows tucked at sides. Push bar down to full extension. Classic tricep isolation.',
      'videoPath': _videoUrl('videos/arms/triceps/cable triceps push down straight bar_x264 (2).mp4'),
    },
    {
      'name': 'Cable Tricep Push Down V Bar',
      'bodyPart': 'Arms',
      'Level': 'Beginner',
      'description': 'V bar gives neutral hand position. Squeeze triceps at full extension.',
      'videoPath': _videoUrl('videos/arms/triceps/cable triceps push down v bar_x264 (2).mp4'),
    },
    {
      'name': 'Dumbbell Overhead Tricep Extension Seated',
      'bodyPart': 'Arms',
      'Level': 'Intermediate',
      'description': 'Lower dumbbell behind head. Places long head under full stretch.',
      'videoPath': _videoUrl('videos/arms/triceps/dumbell overhead extension seated _x264 (2).mp4'),
    },
    {
      'name': 'Dumbbell Tricep Kickback',
      'bodyPart': 'Arms',
      'Level': 'Intermediate',
      'description': 'Extend arm fully behind you. Targets tricep in shortened position.',
      'videoPath': _videoUrl('videos/arms/triceps/dumbell tricep kick back right_x264 (2).mp4'),
    },
    {
      'name': 'Close Grip Barbell Bench Press',
      'bodyPart': 'Arms',
      'Level': 'Advanced',
      'description': 'Shoulder width grip shifts emphasis to triceps allowing very heavy loading.',
      'videoPath': _videoUrl('videos/arms/triceps/close grip barbell bench press_x264 (2).mp4'),
    },
    {
      'name': 'EZ Bar Overhead Tricep Extension',
      'bodyPart': 'Arms',
      'Level': 'Advanced',
      'description': 'Maximally stretches long head of tricep for superior muscle growth.',
      'videoPath': _videoUrl('videos/arms/triceps/ez bar overhead extensions standing _x264 (2).mp4'),
    },
    {
      'name': 'Tricep Dip Machine',
      'bodyPart': 'Arms',
      'Level': 'Intermediate',
      'description': 'Machine guides movement. Excellent for training to failure safely.',
      'videoPath': _videoUrl('videos/arms/triceps/tricep dip machine (2).mp4'),
    },
    {
      'name': 'Wrist Curl Barbell',
      'bodyPart': 'Arms',
      'Level': 'Beginner',
      'description': 'Targets wrist flexors. Critical for grip strength.',
      'videoPath': _videoUrl('videos/arms/forearms/wrist curl barbell _x264 (2).mp4'),
    },
    // SHOULDERS
    {
      'name': 'Lateral Raises Dumbbell',
      'bodyPart': 'Shoulders',
      'Level': 'Beginner',
      'description': 'Premier exercise for medial deltoid responsible for shoulder width.',
      'videoPath': _videoUrl('videos/shoulder/Deltoids/lateral raises dumbell_x264 (2).mp4'),
    },
    {
      'name': 'Dumbbell Seated Shoulder Press',
      'bodyPart': 'Shoulders',
      'Level': 'Beginner',
      'description': 'Seated position isolates shoulders. Foundational overhead pressing movement.',
      'videoPath': _videoUrl('videos/shoulder/Deltoids/seated shoulders press_x264 (2).mp4'),
    },
    {
      'name': 'Front Raises Dumbbell Seated',
      'bodyPart': 'Shoulders',
      'Level': 'Beginner',
      'description': 'Raise arms forward to shoulder height. Isolates anterior deltoid.',
      'videoPath': _videoUrl('videos/shoulder/Deltoids/front raises dumbell seated_x264 (2).mp4'),
    },
    {
      'name': 'Dumbbell Shrugs',
      'bodyPart': 'Shoulders',
      'Level': 'Beginner',
      'description': 'Elevate shoulders toward ears. Directly targets trapezius.',
      'videoPath': _videoUrl('videos/shoulder/Deltoids/dumbell shrugs_x264 (2).mp4'),
    },
    {
      'name': 'Arnold Press Dumbbell',
      'bodyPart': 'Shoulders',
      'Level': 'Intermediate',
      'description': 'Rotation through the press recruits all three deltoid heads. Named after Arnold.',
      'videoPath': _videoUrl('videos/shoulder/Deltoids/arnold press dumbell_x264 (2).mp4'),
    },
    {
      'name': 'Upright Row Barbell',
      'bodyPart': 'Shoulders',
      'Level': 'Intermediate',
      'description': 'Pull bar to chin leading with elbows. Targets lateral deltoids and upper traps.',
      'videoPath': _videoUrl('videos/shoulder/Deltoids/upright row barbell_x264 (2).mp4'),
    },
    {
      'name': 'Upright Row Dumbbell',
      'bodyPart': 'Shoulders',
      'Level': 'Intermediate',
      'description': 'Dumbbell version reduces impingement risk. Upper trap and lateral delt development.',
      'videoPath': _videoUrl('videos/shoulder/Deltoids/upright row dumbell_x264 (2).mp4'),
    },
    {
      'name': 'Bent Over Rear Delt Fly Dumbbell',
      'bodyPart': 'Shoulders',
      'Level': 'Intermediate',
      'description': 'Targets posterior deltoid - most commonly underdeveloped shoulder head.',
      'videoPath': _videoUrl('videos/shoulder/Deltoids/bent over rear delt fly dumbell_x264 (2).mp4'),
    },
    {
      'name': 'Cable Lateral Raises',
      'bodyPart': 'Shoulders',
      'Level': 'Intermediate',
      'description': 'Cable maintains constant tension unlike dumbbells. Superior medial delt stimulation.',
      'videoPath': _videoUrl('videos/shoulder/Deltoids/cable lateral raises_x264 (2).mp4'),
    },
    {
      'name': 'Face Pull Cable',
      'bodyPart': 'Shoulders',
      'Level': 'Intermediate',
      'description': 'Pull rope to face flaring elbows. Targets rear delts and rotator cuff.',
      'videoPath': _videoUrl('videos/shoulder/Deltoids/face pull with resistance band cable_x264 (2).mp4'),
    },
    {
      'name': 'Seated Military Press Barbell',
      'bodyPart': 'Shoulders',
      'Level': 'Intermediate',
      'description': 'Seated with back support. Cornerstone of shoulder strength training.',
      'videoPath': _videoUrl('videos/shoulder/Deltoids/seated miltary press barbell_x264 (2).mp4'),
    },
    {
      'name': 'Standing Shoulder Press Barbell',
      'bodyPart': 'Shoulders',
      'Level': 'Advanced',
      'description': 'Standing press requires total body stability. Most functional overhead pressing measure.',
      'videoPath': _videoUrl('videos/shoulder/Deltoids/standing shoulder press barbell_x264 (2).mp4'),
    },
    {
      'name': 'Standing Shoulder Press Dumbbell',
      'bodyPart': 'Shoulders',
      'Level': 'Intermediate',
      'description': 'Challenges core stability. Each shoulder works through natural range of motion.',
      'videoPath': _videoUrl('videos/shoulder/Deltoids/standing shoulder press dumbell_x264 (2).mp4'),
    },
    {
      'name': 'Barbell Shrugs',
      'bodyPart': 'Shoulders',
      'Level': 'Intermediate',
      'description': 'Heavier loading than dumbbells for maximum trapezius development.',
      'videoPath': _videoUrl('videos/shoulder/Deltoids/barbell shrugs_x264 (2).mp4'),
    },
    {
      'name': 'Machine Lateral Raise',
      'bodyPart': 'Shoulders',
      'Level': 'Beginner',
      'description': 'Machine guides movement with constant tension. Ideal for beginners.',
      'videoPath': _videoUrl('videos/shoulder/Deltoids/machine lateral raise_x264 (2).mp4'),
    },
    {
      'name': 'Landmine Press',
      'bodyPart': 'Shoulders',
      'Level': 'Advanced',
      'description': 'Angled movement easier on shoulder joint. Good for athletes with shoulder issues.',
      'videoPath': _videoUrl('videos/shoulder/Deltoids/landmine press_x264 (2).mp4'),
    },
    {
      'name': 'Seated Rear Delt Fly',
      'bodyPart': 'Shoulders',
      'Level': 'Intermediate',
      'description': 'Seated torso on thighs. Critical for balanced shoulder development.',
      'videoPath': _videoUrl('videos/shoulder/Deltoids/seated rear delt fly_x264 (2).mp4'),
    },
    // CORE
    {
      'name': 'Plank',
      'bodyPart': 'Core',
      'Level': 'Beginner',
      'description': 'Foundation core exercise. Hold straight line from head to heels engaging abs and glutes.',
      'videoPath': _videoUrl('videos/core/plank 1_x264 (2).mp4'),
    },
    {
      'name': 'Sit Up',
      'bodyPart': 'Core',
      'Level': 'Beginner',
      'description': 'Curl entire torso toward knees. Trains rectus abdominis through full range.',
      'videoPath': _videoUrl('videos/core/sit up 1_x264 (2).mp4'),
    },
    {
      'name': 'Ab Crunch',
      'bodyPart': 'Core',
      'Level': 'Beginner',
      'description': 'Curl only shoulders off floor. Constant tension on abdominals.',
      'videoPath': _videoUrl('videos/core/ab crunch_x264 (2).mp4'),
    },
    {
      'name': 'Mountain Climbers',
      'bodyPart': 'Core',
      'Level': 'Beginner',
      'description': 'Alternating knee drives in plank position. Core stability under dynamic conditions.',
      'videoPath': _videoUrl('videos/core/mountain climbers 1_x264 (2).mp4'),
    },
    {
      'name': 'Bicycle Crunches',
      'bodyPart': 'Core',
      'Level': 'Intermediate',
      'description': 'Rotating crunch targets obliques. Consistently ranked among most effective ab exercises.',
      'videoPath': _videoUrl('videos/core/bicycles crunches_x264 (2).mp4'),
    },
    {
      'name': 'Leg Raises Lying',
      'bodyPart': 'Core',
      'Level': 'Intermediate',
      'description': 'Raise straight legs to vertical then lower slowly. Most effective for lower abs.',
      'videoPath': _videoUrl('videos/core/lyinng leg raise 1_x264 (2).mp4'),
    },
    {
      'name': 'Russian Twist',
      'bodyPart': 'Core',
      'Level': 'Intermediate',
      'description': 'Rotate torso side to side with feet elevated. Directly targets obliques.',
      'videoPath': _videoUrl('videos/core/russian twist 1_x264 (2).mp4'),
    },
    {
      'name': 'Hanging Leg Raises',
      'bodyPart': 'Core',
      'Level': 'Intermediate',
      'description': 'Hang from bar and raise straight legs. Most effective for lower abdominal development.',
      'videoPath': _videoUrl('videos/core/hanging leg raises _x264 (2).mp4'),
    },
    {
      'name': 'Hanging Knee Raises',
      'bodyPart': 'Core',
      'Level': 'Intermediate',
      'description': 'Bent knee version. Progression step between floor work and full hanging leg raises.',
      'videoPath': _videoUrl('videos/core/hanging knee raises _x264 (2).mp4'),
    },
    {
      'name': 'Flutter Kicks',
      'bodyPart': 'Core',
      'Level': 'Intermediate',
      'description': 'Rapid alternating leg kicks. Sustained tension on lower abs and hip flexors.',
      'videoPath': _videoUrl('videos/core/flutter kicks 1_x264 (2).mp4'),
    },
    {
      'name': 'Dead Bug',
      'bodyPart': 'Core',
      'Level': 'Intermediate',
      'description': 'Opposite arm and leg lower simultaneously. Teaches anti-extension core stability.',
      'videoPath': _videoUrl('videos/core/dead bug 1_x264 (2).mp4'),
    },
    {
      'name': 'V Up',
      'bodyPart': 'Core',
      'Level': 'Advanced',
      'description': 'Simultaneously raise legs and torso forming a V shape. Full abdominal contraction.',
      'videoPath': _videoUrl('videos/core/v up 1_x264 (2).mp4'),
    },
    {
      'name': 'Jack Knives',
      'bodyPart': 'Core',
      'Level': 'Advanced',
      'description': 'Bring hands and feet together above midpoint. Simultaneous upper and lower ab activation.',
      'videoPath': _videoUrl('videos/core/jack knives_x264 (2).mp4'),
    },
    {
      'name': 'Decline Sit Up Bodyweight',
      'bodyPart': 'Core',
      'Level': 'Advanced',
      'description': 'Decline angle increases range of motion and resistance compared to flat sit ups.',
      'videoPath': _videoUrl('videos/core/decline sit ups bodyweight_x264 (2).mp4'),
    },
    {
      'name': 'Side Plank',
      'bodyPart': 'Core',
      'Level': 'Intermediate',
      'description': 'Lateral core hold. Trains obliques and quadratus lumborum for spinal stability.',
      'videoPath': _videoUrl('videos/core/side plank left 1_x264 (2).mp4'),
    },
    {
      'name': 'Oblique Crunch',
      'bodyPart': 'Core',
      'Level': 'Beginner',
      'description': 'Curl shoulder diagonally toward opposite knee. Directly targets side abdominals.',
      'videoPath': _videoUrl('videos/core/oblique crunch 1_x264 (2).mp4'),
    },
  ];
}